### ISSUE TITLE
Kurumi's Shrine (Night)

### ISSUE THREAD

**Issue by n0k0m3** [respectZ/date-a-live#3]
CHOICES
Search near the Shrine entrance.
Look inside the shrine.
Search in the courtyard behind the shrine

CHOICES
Kurumi, let's hang a prayer stick for good luck.
Ask a monk with the gift of prophecy.
Have you considered drawing fortune sticks?

CHOICES
Open the scary old window.
Search behind the deity statue.
Check out the abandoned room.

CHOICES
They say flipping a coin to a treasure toad can change your luck.
Why is Kurumi so happy?
Maybe taking a walk by the seaside will bring inspiration

CHOICES
I hear there's a great food street nearby.
Come back tomorrow.

CHOICES
Red stick
Yellow stick
Purple stick

CHOICES
Tell her the god is angry and we need to leave.
The voice is suspicious, but searching for the object is more important.
Walk up behind Kurumi and try to scare her.

CHOICES
Dash forward with speed.
Walk lightly on tip-toes.
Crawl with all limbs on the ground
Walk horizontally like a crab

CHOICES
Touch her left hand, waist and right leg.
Touch her head, stomach and right leg.

CHOICES
Maybe what you're looking for is hidden here?
Go to the ancient well rumored to show the future under moonlight
So, the moon is quite pretty tonight

CHOICES
If you want to have a full meal, ramen is the best choice.
Eat takoyaki
But as long as I'm not on the menu.

CHOICES
This is it! Open it up!
It looks suspicious, inspect further.
Tap on the ground tile first.

CHOICES
There's something suspicious about the things piled nearby.
There's light at the end of the passage, let's check it out.

CHOICES
Don't give up, try to climb out
Stop struggling and fall into the whole

CHOICES
I see the moon
I see a strange shadow
I see Kurumi

CHOICES
You're just as indecipherable
Even if you are a fairy girl, I'll still go on a date with you.
Kurumi is cuter than the fairy girl.

CHOICES
Under the rock
Kurumi looks like a pirate
Next to the big tree

CHOICES
It must taste really bad...I'll go talk to the manager.
Maybe my ramen will be up to Kurumi's standards?

CHOICES
Luckily we haven't gone that far, I'll go back and buy you another one.
I haven't eaten any of my takoyaki.

CHOICES
Why don't we use a crowbar to open it?
Destroy the box with weapons.
Use Yud to explore the chest's memories.

CHOICES
Maybe we should wait until morning.
Looks like it's sealing a terrible demon.
Make up a scary story to scare Kurumi

CHOICES
Try washing it clean.
Useless old cloth

CHOICES
Push Kurumi up against the wall and cover her face
Hide her face with a kiss
Ask Kotori for help

CHOICES
Keep searching
Come back tomorrow when the light is better.

CHOICES
Lightly press down
Forcefully pull it out

CHOICES
Kurumi is too cute
I like Kurumi's underwear
I think the atmosphere is a little scary today

CHOICES
Kurumi is a little scary
I want to learn more about Kurumi, even just a little bit.

CHOICES
I would love another date
Think about it

**Comment by respectZ** [comment]
wew thanks a lot dude !
and also good job for the dump
